name: Continuous Integration

on:
  push:
    branches: [ v2.x ]
  pull_request:
    branches: [ v2.x ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.1"]
        librdkafka: [ v1.8.2]
        extrdkafka: [6.0.0]
        laravel: [9]

    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
        run:
          make version-test-9-${{ matrix.php }}-${{ matrix.librdkafka }}-${{ matrix.extrdkafka }}-${{ matrix.laravel }}
